apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hack-on-stonesoup-component-build
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hack-on-stonesoup-component-build
    app.kubernetes.io/part-of: test-application
  name: hack-on-stonesoup-component-build
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: hack-on-stonesoup-component-build
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hack-on-stonesoup-component-build
    spec:
      containers:
      - image: quay.io/tkdchen/hack-on-stonesoup-component-build
        imagePullPolicy: Always
        name: container-image
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
